language: node_js
node_js: stable

install:
  - npm install --save bluebird

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "zahnghTK"
  - git config user.email "510223064@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/zhanghTK/zhanghTK.github.io.git
